{*******************************************************}
{                                                       }
{       Delphi Visual Component Library                 }
{       Custom Containers Pack (CCPack)                 }
{                                                       }
{       Copyright (c) 1997-99, Sergey Orlik             }
{                                                       }
{     Written by:                                       }
{       Sergey Orlik                                    }
{       product manager                                 }
{       Russia, C.I.S. and Baltic States (former USSR)  }
{       Inprise Moscow office                           }
{       e-mail:  sorlik@inprise.ru                      }
{       WWW: http://www.inprise.ru                      }
{                                                       }
{       Personal Home Page:                             }
{       www.geocities.com/SiliconValley/Way/9006/       }
{                                                       }
{*******************************************************}

{$i Delphiversions.inc}

//======================================
// VCL Version Define

{$IFDEF DELPHI5_UP}
      {$DEFINE VER_VCL5}
      {$DEFINE VER_D}
{$ELSE}
'Versions older than Delphi5 are no longer supported.'
'You might be able to find a ccpack version for Delphi 4 on code central.'
{$ENDIF}

